image:
  file: .gitpod.Dockerfile

tasks:
  - init: 'yarn install'
    command: |
      echo ENVIRONMENT=$NODE_ENV >> .env
      echo JWT_SECRET=$JWT_SECRET >> .env
      echo PORT=$PORT >> .env
      yarn db_init
      yarn start
ports:
  - port: 9000
